### ISSUE TITLE
Gretty scanner(s) fail in 2.3.0 with kotlin project

### ISSUE THREAD

**Issue by DALDEI** [gretty-gradle-plugin/gretty#102]
Likely related to issue #99 , but I do not have any special scanning configuations and cannot find a workaround.  I tried setting scanner to jetty and jdk,  different errors but clearly related.

Example from jdk scanner
```

        Suppressed: java.lang.RuntimeException: Error scanning entry com/aspose/imaging/internal/aZ/bN.class from jar file:///home/dlee/.gradle/caches/modules-2/files-2.1/com.aspose/aspose-imaging/18.4/7cb1869a7799748b07a41675f9a662a42e0e3b37/aspose-imaging-18.4-jdk16.jar
                at org.eclipse.jetty.annotations.AnnotationParser.lambda$parseJar$0(AnnotationParser.java:882) ~[jetty-annotations-9.4.14.v20181114.jar:9.4.14.v20181114]
                at java.util.TreeMap$ValueSpliterator.forEachRemaining(TreeMap.java:2897) ~[na:1.8.0_181]
                at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[na:1.8.0_181]
                at org.eclipse.jetty.annotations.AnnotationParser.parseJar(AnnotationParser.java:874) ~[jetty-annotations-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:838) ~[jetty-annotations-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163) ~[jetty-annotations-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:471) ~[jetty-annotations-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765) ~[jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
                at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683) ~[jetty-util-9.4.14.v20181114.jar:9.4.14.v20181114]
                at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
        Caused by: java.lang.IllegalArgumentException: null
                at org.objectweb.asm.ClassVisitor.<init>(ClassVisitor.java:69)
                at org.objectweb.asm.ClassVisitor.<init>(ClassVisitor.java:56)
                at org.eclipse.jetty.annotations.AnnotationParser$MyClassVisitor.<init>(AnnotationParser.java:476)
                at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:935)
                at org.eclipse.jetty.annotations.AnnotationParser.parseJarEntry(AnnotationParser.java:919)
                at org.eclipse.jetty.annotations.AnnotationParser.lambda$parseJar$0(AnnotationParser.java:878)
                ... 9 common frames omitted

```

This type of errror is common for reflection based code that does full class walking -- there are some constructs the kotlin compiler produces which cause exceptions in java reflection ( things like lambda functions in anonymous classess) 

gretty 2.3.0
kotlin 1.3.0
gradle 5.0

**Comment by javabrett** [comment]
@DALDEI thanks for the report.  Gretty 2.3.1 has just been released and contains a fix (upgrade to ASM 7.0) for Jetty 9.4.13/9.4.14 which also contain the ASM 7.0 upgrade.

Not saying that this will fix this issue for sure (we have no Kotlin tests at the moment), but if you could give Gretty 2.3.1 a test and report-back that would be great.

**Comment by DALDEI** [comment]
This is working perfectly so far !!!!
