### ISSUE TITLE
Bug: HotReload Exception with Composite Build

### ISSUE THREAD

**Issue by gbalthasar** [gretty-gradle-plugin/gretty#104]
[CompositeBuildGrettyExample.zip](https://github.com/gretty-gradle-plugin/gretty/files/2666903/CompositeBuildGrettyExample.zip)

Hi,
using
- Windows 10
- JDK 8
- Gradle 2.4.12
- Gretty 2.3.1
- Tomcat 8.5

a composite build structure throws Exception upon hot reload of my WebApp after continues build recompiles the lib. I included an example project structure (see .zip) to reproduce:

1. Extract somewhere
2. New Console/CMD at '\lib\greeter': gradle -t build
3. New Console/CMD at '\web\hello': gradle apprunwar
4. http://localhost:8080/hello shows 'Hello Gradle!'
5. Change return value at '\lib\greeter' Greeter.java say() Method from "Gradle" to "Gretty" and save file
6. Continues Build rebuilds
7. Gretty tries to reload war but fails with exception:

```
org.akhikhl.gretty.JettyScannerManager$1@55df6fbb failed on '[G:\temp\lib\greeter\build\libs\greeter-1.0.0.jar]
java.lang.IllegalStateException: Resolving configuration 'implementation' directly is not allowed
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.assertResolvingAllowed(DefaultConfiguration.java:897)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:435)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getResolvedConfiguration(DefaultConfiguration.java:430)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getResolvedConfiguration(Unknown Source)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaBeanProperty.getProperty(MetaBeanProperty.java:59)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:228)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryGetProperty(BeanDynamicObject.java:171)
        at org.gradle.internal.metaobject.CompositeDynamicObject.tryGetProperty(CompositeDynamicObject.java:55)
        at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:59)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getProperty(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:50)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:296)
        at org.akhikhl.gretty.scanner.BaseScannerManager$_scanFilesChanged_closure3.doCall(BaseScannerManager.groovy:158)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:42)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.BooleanReturningMethodInvoker.invoke(BooleanReturningMethodInvoker.java:51)
        at org.codehaus.groovy.runtime.callsite.BooleanClosureWrapper.call(BooleanClosureWrapper.java:53)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.findAll(DefaultGroovyMethods.java:4331)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.findAll(DefaultGroovyMethods.java:4203)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.findAll(DefaultGroovyMethods.java:4188)
        at org.codehaus.groovy.runtime.dgm$203.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:274)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.akhikhl.gretty.scanner.BaseScannerManager.scanFilesChanged(BaseScannerManager.groovy:157)
        at org.akhikhl.gretty.JettyScannerManager.scanFilesChangedOverride(JettyScannerManager.groovy:57)
        at org.akhikhl.gretty.JettyScannerManager$1.filesChanged(JettyScannerManager.groovy:33)
        at org.eclipse.jetty.util.Scanner.reportBulkChanges(Scanner.java:691)
        at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:551)
        at org.eclipse.jetty.util.Scanner.scan(Scanner.java:403)
        at org.eclipse.jetty.util.Scanner$1.run(Scanner.java:353)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
```

8. Workaround by change index.jsp at '\web\hello' and save
9. Gretty reloads correctly now
10. http://localhost:8080/hello shows 'Hello Gretty!'

Please fix as I need this feature for our development with shared/distributed libraries. At the moment we are using the 'old' original Gretty plugin as we are still at JDK 7 there but once we completly switch to JDK 8 and Tomcat 8.5 we need the official as the 'old' one doesn't support newer Tomcats.

Thank you very much! Regards,
gbalthasar

**Comment by javabrett** [comment]
Thanks for the report.  Can you:
- Update above with a more complete stacktrace
- Confirm whether or not the problem occurs when running Gradle 4.10.2 or 5.0.0.

**Comment by gbalthasar** [comment]
Thanks for the fast reply. I have:

- Updated the exception with full stacktrace (see initial post)
- Tested Gradle 4.10.2 and Gradle 5.0.0 and with both versions the same exception occurs

**Comment by javabrett** [comment]
I think this was introduced by 1531ea08cf583879cd784d206d09d59bc4bba73e, which was replacing the deprecated `compile` configuration with `implementation`.  In the code in-question here, I think it probably needs to be `compileClasspath`.

**Comment by gbalthasar** [comment]
I think this is the actual problem, see also https://stackoverflow.com/questions/47910578/not-able-to-copy-configurations-dependencies-after-upgrading-gradle-plugin-for-a?rq=1

Solutions there point out to use compileClasspath instead or to extend an own configuration from implementation. I don't know which approach is better for the future, so it doesn't break again with newer Gradle versions:

```
configurations {
  customConfig.extendsFrom implementation
}
```

I hope it gets fixed with the next gretty version 2.3.2. Thank you.

**Comment by tmohme** [comment]
Same problem here with a "simple" multi-project build (Gradle 5.1.1, gretty-gradle-plugin 2.3.1, task "appRun") when changing the code in one of the projects and doing a "./gradlew build".

Complete stacktrace:
```
java.lang.IllegalStateException: Resolving configuration 'implementation' directly is not allowed
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.assertIsResolvable(DefaultConfiguration.java:1198)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveToStateOrLater(DefaultConfiguration.java:529)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getResolvedConfiguration(DefaultConfiguration.java:524)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getResolvedConfiguration(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaBeanProperty.getProperty(MetaBeanProperty.java:59)
	at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:228)
	at org.gradle.internal.metaobject.BeanDynamicObject.tryGetProperty(BeanDynamicObject.java:171)
	at org.gradle.internal.metaobject.CompositeDynamicObject.tryGetProperty(CompositeDynamicObject.java:55)
	at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:59)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getProperty(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:298)
	at org.akhikhl.gretty.scanner.BaseScannerManager$_scanFilesChanged_closure3.doCall(BaseScannerManager.groovy:158)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.call(PogoMetaClassSite.java:41)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.BooleanReturningMethodInvoker.invoke(BooleanReturningMethodInvoker.java:51)
	at org.codehaus.groovy.runtime.callsite.BooleanClosureWrapper.call(BooleanClosureWrapper.java:53)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.findAll(DefaultGroovyMethods.java:4892)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.findAll(DefaultGroovyMethods.java:4764)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.findAll(DefaultGroovyMethods.java:4749)
	at org.codehaus.groovy.runtime.dgm$228.invoke(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:246)
	at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:55)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at org.akhikhl.gretty.scanner.BaseScannerManager.scanFilesChanged(BaseScannerManager.groovy:157)
	at org.akhikhl.gretty.JettyScannerManager.scanFilesChangedOverride(JettyScannerManager.groovy:57)
	at org.akhikhl.gretty.JettyScannerManager$1.filesChanged(JettyScannerManager.groovy:33)
	at org.eclipse.jetty.util.Scanner.reportBulkChanges(Scanner.java:691)
	at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:551)
	at org.eclipse.jetty.util.Scanner.scan(Scanner.java:403)
	at org.eclipse.jetty.util.Scanner$1.run(Scanner.java:353)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
```

Our workaround is, to go back to gretty-gradle-plugin 2.1.0 and convert "implementation" dependencies to "compile".  
The [gradle documentation](https://docs.gradle.org/current/userguide/java_plugin.html#sec:java_plugin_and_dependency_management) has a diagram with coloured boxes that explains the connection between the various configurations and explains, which configuration should (must) be used for which purpose.   
According to the docs, "compileClasspath" and "runtimeClassPath" are intended "for consumption by tasks", while "implementation" is meant to declare dependencies against.

**Comment by tmohme** [comment]
Now that my [PR](https://github.com/gretty-gradle-plugin/gretty/pull/113) finally passed travis-ci, it would be great if could make progress here.

**Comment by tmohme** [comment]
We are coming to the limits of our workaround for this problem.
To make a good decision for which way to continue, we need to know if (and when) my PR will find its way into the project.

**Comment by gbalthasar** [comment]
We need to migrate within the next 3 month. I need a statement whether gretty will be developed on and this bug will be solved or not. It's the base for our decision whether to stay with gretty or try to find another solution that works for us.

**Comment by fokkoru** [comment]
Hey, any updates for this bug, I faced the same problem?

**Comment by javabrett** [comment]
@fokkoru JDK, Gradle, Gretty and Container versions please.

**Comment by fokkoru** [comment]
Gretty v. 3.0.1
```
$ ./gradlew -v

------------------------------------------------------------
Gradle 5.6.4
------------------------------------------------------------

Build time:   2019-11-01 20:42:00 UTC
Revision:     dd870424f9bd8e195d614dc14bb140f43c22da98

Kotlin:       1.3.41
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.14 compiled on March 12 2019
JVM:          1.8.0_222 (AdoptOpenJDK 25.222-b10)
OS:           Mac OS X 10.15.2 x86_64
```

**Comment by fokkoru** [comment]
Hey, @javabrett, any luck finding this bug, can I help you with it?

**Comment by gbalthasar** [comment]
Manually tested the Pull Request, see https://github.com/gretty-gradle-plugin/gretty/pull/113#issuecomment-691355771
