### ISSUE TITLE
hot deployment "managedClassReload=true" throws exception

### ISSUE THREAD

**Issue by kevinjoy89** [gretty-gradle-plugin/gretty#118]
Hi! Thanks for the great plugin, but I have an issue with its hot deployment feature, which I have described here as well. The issue is as follows:
 I want to use the hot deployment in my project, but i'm not able to use hot deployment with Gretty, despite setting the managedClassReload=true. When i run the application by using tomcatRunDebug or tomcatRunWarDebug or appRunDebug gretty task from IDEA, the project throws a exception as follows:
`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'baseService' defined in class path resource [spring/spring-ibatis.xml]: Initialization of bean failed; nested exception is org.springframework.aop.framework.AopConfigException: Unexpected AOP exception; nested exception is java.lang.IllegalStateException: Unable to load cache item
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:866)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:542)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443)
	at com.yinhai.project.listener.StartupListener.configureAndRefreshWebApplicationContext(StartupListener.java)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325)
	at com.yinhai.project.listener.StartupListener.initWebApplicationContext(StartupListener.java)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
	at com.yinhai.project.listener.StartupListener.contextInitialized(StartupListener.java:25)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4792)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5256)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1423)
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1413)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.springframework.aop.framework.AopConfigException: Unexpected AOP exception; nested exception is java.lang.IllegalStateException: Unable to load cache item
	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:219)
	at org.springframework.aop.framework.ProxyFactory.getProxy(ProxyFactory.java:109)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.createProxy(AbstractAutoProxyCreator.java:469)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.wrapIfNecessary(AbstractAutoProxyCreator.java:349)
	at org.springframework.aop.framework.autoproxy.AbstractAutoProxyCreator.postProcessAfterInitialization(AbstractAutoProxyCreator.java:298)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsAfterInitialization(AbstractAutowireCapableBeanFactory.java:423)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1633)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555)
	... 23 common frames omitted
Caused by: java.lang.IllegalStateException: Unable to load cache item
	at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:79)
	at org.springframework.cglib.core.internal.LoadingCache.get(LoadingCache.java:34)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData.get(AbstractClassGenerator.java:116)
	at org.springframework.cglib.core.AbstractClassGenerator.create(AbstractClassGenerator.java:291)
	at org.springframework.cglib.proxy.Enhancer.createHelper(Enhancer.java:480)
	at org.springframework.cglib.proxy.Enhancer.createClass(Enhancer.java:337)
	at org.springframework.aop.framework.ObjenesisCglibAopProxy.createProxyClassAndInstance(ObjenesisCglibAopProxy.java:55)
	at org.springframework.aop.framework.CglibAopProxy.getProxy(CglibAopProxy.java:203)
	... 30 common frames omitted
Caused by: java.lang.NoSuchFieldError: r$sfields
	at com.yinhai.sysframework.service.BaseService$$EnhancerBySpringCGLIB$$3d4f9b9e.<clinit>(<generated>)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.springframework.cglib.core.ReflectUtils.defineClass(ReflectUtils.java:415)
	at org.springframework.cglib.core.AbstractClassGenerator.generate(AbstractClassGenerator.java:336)
	at org.springframework.cglib.proxy.Enhancer.generate(Enhancer.java:492)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:93)
	at org.springframework.cglib.core.AbstractClassGenerator$ClassLoaderData$3.apply(AbstractClassGenerator.java:91)
	at org.springframework.cglib.core.internal.LoadingCache$2.call(LoadingCache.java:54)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.springframework.cglib.core.internal.LoadingCache.createEntry(LoadingCache.java:61)
	... 37 common frames omitted
10:16:07 INFO  springloaded shutdown: null`
It does not matter whether I use tomcat8 or tomcat85 or tomcat9 or jetty9 for servlet container,my project throws the same exception and can't work.
When I run the application by using appRun or appRunWar or tomcatRunWar gretty task from IDEA, the project doesn't throw any exception and worked successful. But the logs does not show that the changes to source files in project are detected by Gretty.
Interesingly enough, when I comment out the managedClassReload=true line,the changes to source files are detected and the project is automatically restart.My build.gradle is as follows:
`
//use Gradle 5.1.1 and jdk8 in SpringMVC project.
plugins {
    id 'java'
    id 'war'
    id "org.gretty" version "2.3.1"
}

gretty {
    //access port
    httpPort = 8080
    //project name
    contextPath = "/dldplus"
    //servlet container,support tomcat7/8/85/9、jetty7/8/9/9.3/9.4
    servletContainer = "tomcat85"
    //open hot deployment
    managedClassReload = true
    scanInterval = 1
    recompileOnSourceChange = true
    reloadOnClassChange = true
    reloadOnConfigChange = true
    reloadOnLibChange = true
    fastReload = true
}
`
What can be the cause for gretty's hot deployment not working? Does springloaded not work together with SpringMVC project?

**Comment by gbalthasar** [comment]
At the moment (as gretty has some problems/bugs) you have two options imho:

1. Running with managedClassReload=true and apprun
2. Running with managedClassReload=false and apprunwar

Second may have other problems like reloading complete app context when you change a JSP. Or some resources not available because excluded for your production war.

For getting 1. to run you need to add following to your build (copied and improved from issue):

```
task sync(type: Sync) {
	dependsOn build
	from "$sourceSets.main.java.outputDir"
	into "${project.buildDir}/inplaceWebapp/WEB-INF/classes"
}
project.afterEvaluate {
	tasks.appRun {
		dependsOn sync
	}
}
```
