### ISSUE TITLE
`appRun` fails with Exception in thread "main" java.lang.NoClassDefFoundError: groovy/util/CliBuilder

### ISSUE THREAD

**Issue by umbertooo** [gretty-gradle-plugin/gretty#123]
I'm new to Gradle and making my first steps with Gretty. Running `./gradlew appRun` I get this exception:

```
Exception in thread "main" java.lang.NoClassDefFoundError: groovy/util/CliBuilder
        at org.akhikhl.gretty.Runner.main(Runner.groovy:40)
Caused by: java.lang.ClassNotFoundException: groovy.util.CliBuilder
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 1 more
Exception in thread "Thread-99" org.gradle.process.internal.ExecException: Process 'command '/Users/username/.sdkman/candidates/java/8.0.212-zulu/bin/java'' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:396)
        at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:37)
        at org.gradle.api.internal.file.DefaultFileOperations.javaexec(DefaultFileOperations.java:227)
        at org.gradle.api.internal.project.DefaultProject.javaexec(DefaultProject.java:1105)
        at org.gradle.api.internal.project.DefaultProject.javaexec(DefaultProject.java:1100)
        at org.gradle.api.Project$javaexec$5.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
        at org.akhikhl.gretty.DefaultLauncher.javaExec(DefaultLauncher.groovy:93)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:352)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:68)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168)
        at org.akhikhl.gretty.LauncherBase$_launchThread_closure4.doCall(LauncherBase.groovy:259)
        at org.akhikhl.gretty.LauncherBase$_launchThread_closure4.doCall(LauncherBase.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:104)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:326)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041)
        at groovy.lang.Closure.call(Closure.java:411)
        at groovy.lang.Closure.call(Closure.java:405)
        at groovy.lang.Closure.run(Closure.java:492)
        at java.lang.Thread.run(Thread.java:748)
<===========--> 90% EXECUTING [3s]
> :backend:appRun
> IDLE
```

Is this a Gretty related problem? I already reinstalled Java and Gradle. Find the repository at https://github.com/umbertooo/gretty-webpack-springboot

Hopefully you can help me with this.

```
» java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (Zulu 8.38.0.13-CA-macosx) (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (Zulu 8.38.0.13-CA-macosx) (build 25.212-b04, mixed mode)

» ./gradlew --version

------------------------------------------------------------
Gradle 5.2.1
------------------------------------------------------------

Build time:   2019-02-08 19:00:10 UTC
Revision:     f02764e074c32ee8851a4e1877dd1fea8ffb7183

Kotlin DSL:   1.1.3
Kotlin:       1.3.20
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_212 (Azul Systems, Inc. 25.212-b04)
OS:           Mac OS X 10.14.5 x86_64
```

**Comment by pbit** [comment]
Hi,

this exception hit me too while migrating an project from maven to gradle.

As I am not a groovy guy take my current findings with care ;)

This issue seems to be caused by the groovy version.
The class `groovy.util.CliBuilder`is deprecated since groovy 2.5 [artticle on dzone](https://dzone.com/articles/groovy-25-clibuilder-renewal)

The gretty plugin declares a dependency on `org.codehaus.groovy:groovy:2.4.15` which includes this class.
Since gradle 5 the internal groovy version was updated to 2.5.x and this class now lives in `org.codehaus.groovy:groovy-cli-commons`

If you just add the `war` and `org.gretty` plugins to the build evrything seems to work, as the gretty version of groovy is used.

As soon as you add an plugin which uses groovy 2.5 everything breaks.
In your case its the `io.spring.dependency-management` plugin which declares a dependency on `groovyLocal()`. So the groovy version of gradle is used (and overrides the transitive dependency of the gretty plugin ?).

I think there is not much we can do in our buildscript to solve this (except not to use any plugins with a dependency on groovy > 2.4 ;))

Adding an explicit `import groovy.cli.commons.CliBuilder` in `Runner.groovy` fixes the issue, but requires a dependency on `groovy-all` to cover both versions. As this pulls in a lot of other dependencies I dont think this is a way to go.

The clean path would be an upgrade of grettys groovy dependency to 2.5 (would this drop support for gradle < 5 ?)

Maybe someone from the gretty team can answer this...

**Comment by chuntungho** [comment]
looking forward to the solution

**Comment by MikeN123** [comment]
I 'fixed' this by adding the following to my gradle file:

`
dependencies {
    gretty 'org.codehaus.groovy:groovy-cli-commons:2.5.7'
}
`

**Comment by umbertooo** [comment]
Thanks @MikeN123, your solution works for me.

**Comment by boris-petrov** [comment]
@umbertooo - is this still an issue with Gretty 3.0.3? Please close the issue if not.

**Comment by umbertooo** [comment]
Works on Gretty 3.0.3 without adding the dependency to groovy-cli-commons https://github.com/gretty-gradle-plugin/gretty/issues/123#issuecomment-510038091
