### ISSUE TITLE
In java11, displaying jsp is not supported.

### ISSUE THREAD

**Issue by wangyang1749** [gretty-gradle-plugin/gretty#131]
HTTP ERROR 500
Problem accessing /untitletest/index.jsp. Reason:

    Server Error
Caused by:
org.apache.jasper.JasperException: PWC6033: Error in Javac compilation for JSP

PWC6199: Generated servlet error:
package org.apache.jasper.runtime does not exist

PWC6199: Generated servlet error:
package org.apache.jasper.runtime does not exist

PWC6199: Generated servlet error:
cannot find symbol
  symbol:   class JspFactory
  location: class org.apache.jsp.index_jsp

PWC6199: Generated servlet error:
package org.glassfish.jsp.api does not exist

PWC6199: Generated servlet error:
cannot find symbol
  symbol:   class HttpServletRequest
  location: class org.apache.jsp.index_jsp

PWC6199: Generated servlet error:
cannot find symbol
  symbol:   class HttpServletResponse
  location: class org.apache.jsp.index_jsp

PWC6199: Generated servlet error:
cannot find symbol
  symbol:   class ServletException
  location: class org.apache.jsp.index_jsp

PWC6199: Generated servlet error:
package javax.servlet does not exist

PWC6199: Generated servlet error:
package javax.servlet.http does not exist

PWC6199: Generated servlet error:
package javax.servlet.jsp does not exist

PWC6199: Generated servlet error:
cannot find symbol
  symbol:   variable JspFactory
  location: class org.apache.jsp.index_jsp

PWC6199: Generated servlet error:
cannot find symbol
  symbol:   class PageContext
  location: class org.apache.jsp.index_jsp

PWC6199: Generated servlet error:
cannot find symbol
  symbol:   class HttpSession
  location: class org.apache.jsp.index_jsp

PWC6199: Generated servlet error:
cannot find symbol
  symbol:   class ServletContext
  location: class org.apache.jsp.index_jsp

PWC6199: Generated servlet error:
cannot find symbol
  symbol:   class ServletConfig
  location: class org.apache.jsp.index_jsp

PWC6199: Generated servlet error:
cannot find symbol
  symbol:   class JspWriter
  location: class org.apache.jsp.index_jsp

PWC6199: Generated servlet error:
cannot find symbol
  symbol:   class JspWriter
  location: class org.apache.jsp.index_jsp

PWC6199: Generated servlet error:
cannot find symbol
  symbol:   class PageContext
  location: class org.apache.jsp.index_jsp

PWC6199: Generated servlet error:
package org.glassfish.jsp.api does not exist

PWC6199: Generated servlet error:
cannot find symbol
  symbol:   class SkipPageException
  location: class org.apache.jsp.index_jsp

PWC6199: Generated servlet error:
cannot find symbol
  symbol:   class ServletException
  location: class org.apache.jsp.index_jsp

	at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:129)
	at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:299)
	at org.apache.jasper.compiler.Compiler.generateClass(Compiler.java:392)
	at org.apache.jasper.compiler.Compiler.compile(Compiler.java:453)
	at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:625)
	at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:375)
	at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:473)
	at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:377)
	at org.eclipse.jetty.jsp.JettyJspServlet.service(JettyJspServlet.java:103)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:201)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by javabrett** [comment]
This looks like a problem discussed in https://stackoverflow.com/questions/23394842/jsps-for-embedded-jetty-in-maven-tests-not-compiling .

Can you try adding `-Dorg.apache.jasper.compiler.disablejsr199=true` or other fixes suggested there?
