### ISSUE TITLE
Gradle 6 deprecation warnings

### ISSUE THREAD

**Issue by boris-petrov** [gretty-gradle-plugin/gretty#133]
When running Gretty on Gradle 6 (the `appStart` task), a bunch of deprecation warnings appear:

```
Property 'auxPortRange' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'beforeClassPath' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'classPath' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'consoleLogEnabled' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'contextConfigFile' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'contextPath' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'debug' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'debugPort' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'debugSuspend' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'defaultJacocoEnabled' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'effectiveInplace' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'effectiveInplaceMode' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'enableNaming' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'extraResourceBases' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'fastReload' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'fileLogEnabled' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'host' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'httpEnabled' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'httpIdleTimeout' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'httpPort' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'httpsEnabled' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'httpsIdleTimeout' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'httpsPort' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'initParameters' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'inplace' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'inplaceMode' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'integrationTest' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'interactive' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'interactiveMode' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'jacoco' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'jettyEnvXmlFile' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'jettyXmlFile' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'jvmArgs' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'launcherConfig' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'liveReloadEnabled' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'logDir' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'logFileName' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'logbackConfigFile' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'logbackVersion' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'loggingLevel' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'managedClassReload' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'onScan' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'onScanFilesChanged' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'onStart' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'onStop' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'portPropertiesFileName' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'projectPath' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'randomFreePort' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'realm' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'realmConfigFile' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'recompileOnSourceChange' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'redeployMode' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'reloadOnClassChange' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'reloadOnConfigChange' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'reloadOnLibChange' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'resourceBase' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'runnerClassPath' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'scanDependencies' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'scanDirs' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'scanInterval' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'scanner' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'secureRandom' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'serverConfigFile' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'serverStartInfo' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'servicePort' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'servletContainer' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'singleSignOn' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'springBoot' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'springBootMainClass' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'springBootVersion' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'springLoadedVersion' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'springVersion' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'sslHost' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'sslKeyManagerPassword' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'sslKeyStorePassword' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'sslKeyStorePath' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'sslNeedClientAuth' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'sslTrustStorePassword' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'sslTrustStorePath' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'startConfig' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'statusPort' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'stopCommand' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'systemProperties' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'webInfIncludeJarPattern' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'webXml' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
Property 'webappClassPaths' is not annotated with an input or output annotation. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0.
```

**Comment by boris-petrov** [comment]
Another one:

```
> Configure project :backend
Using method Project#afterEvaluate(Closure) when the project is already evaluated has been deprecated. This will fail with an error in Gradle 7.0. The configuration given is ignored because the project has already been evaluated. To apply this configuration, remove afterEvaluate.
    at org.gradle.api.internal.project.DefaultProject.maybeNagDeprecationOfAfterEvaluateAfterProjectIsEvaluated(DefaultProject.java:1019)
    at org.gradle.api.internal.project.DefaultProject.afterEvaluate(DefaultProject.java:1013)
    at org.gradle.api.Project$afterEvaluate.call(Unknown Source)
    at org.akhikhl.gretty.GrettyPlugin.apply(GrettyPlugin.groovy:807)
    at org.akhikhl.gretty.GrettyPlugin.apply(GrettyPlugin.groovy)
    at org.gradle.api.internal.plugins.ImperativeOnlyPluginTarget.applyImperative(ImperativeOnlyPluginTarget.java:43)
    at org.gradle.api.internal.plugins.RuleBasedPluginTarget.applyImperative(RuleBasedPluginTarget.java:51)
    at org.gradle.api.internal.plugins.DefaultPluginManager.addPlugin(DefaultPluginManager.java:181)
    ...
```

**Comment by javabrett** [comment]
@boris-petrov what remains of these with 3.0.2?

**Comment by boris-petrov** [comment]
@javabrett - all of them. I fixed a couple of others that I didn't mention here. The ones I did are still valid.

**Comment by lipnitsk** [comment]
Also (verified on gradle 6.2 and gretty 3.0.1):
```
The AbstractArchiveTask.baseName property has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the archiveBaseName property instead. See https://docs.gradle.org/6.2/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.html#org.gradle.api.tasks.bundling.AbstractArchiveTask:baseName for more details.
        at org.gradle.api.tasks.bundling.AbstractArchiveTask.setBaseName(AbstractArchiveTask.java:231)
        at org.gradle.api.tasks.bundling.Zip_Decorated.setBaseName(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at groovy.lang.Closure.setProperty(Closure.java:347)
        at org.akhikhl.gretty.ProductConfigurer$_configureProduct_closure2.doCall(ProductConfigurer.groovy:162)

```
```
The AbstractArchiveTask.version property has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the archiveVersion property instead. See https://docs.gradle.org/6.2/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.html#org.gradle.api.tasks.bundling.AbstractArchiveTask:version for more details.
        at org.gradle.api.tasks.bundling.AbstractArchiveTask.setVersion(AbstractArchiveTask.java:306)
        at org.gradle.api.tasks.bundling.Zip_Decorated.setVersion(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at groovy.lang.Closure.setProperty(Closure.java:347)
        at org.akhikhl.gretty.ProductConfigurer$_configureProduct_closure2.doCall(ProductConfigurer.groovy:163)
```
```
The AbstractArchiveTask.destinationDir property has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the destinationDirectory property instead. See https://docs.gradle.org/6.2/dsl/org.gradle.api.tasks.bundling.AbstractArchiveTask.html#org.gradle.api.tasks.bundling.AbstractArchiveTask:destinationDir for more details.
        at org.gradle.api.tasks.bundling.AbstractArchiveTask.setDestinationDir(AbstractArchiveTask.java:196)
        at org.gradle.api.tasks.bundling.Zip_Decorated.setDestinationDir(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at groovy.lang.Closure.setProperty(Closure.java:347)
        at org.akhikhl.gretty.ProductConfigurer$_configureProduct_closure2.doCall(ProductConfigurer.groovy:164)
```

**Comment by lipnitsk** [comment]
Oops these were fixed by @boris-petrov in b94a0d8befa4f262496046576e550462c318d24a

**Comment by po5i** [comment]
Any plans on when will be released this fix?

**Comment by boris-petrov** [comment]
@f4lco, @wolfs - [here is a build](https://pipelines.actions.githubusercontent.com/lsA5HtGujfYpYUq6fs8sgC8h0eXL9AmLPxjdsa64nTCu8RPMUS/_apis/pipelines/1/runs/56/signedlogcontent/3?urlExpires=2021-03-08T11%3A07%3A16.2070938Z&urlSigningMethod=HMACV1&urlSignature=6pRN8RTPl9Jd0BxwAL0%2FIDimcrVeNwv7db0r5%2Bowi9c%3D) on the `master` branch (the same is on `gretty-3.x`). Searching for `deprecated` shows only 3 things that are left to fix (there are 8 matches but only 3 Gradle warnings):

```
> Configure project :libs:gretty
The maven plugin has been deprecated. This is scheduled to be removed in Gradle 7.0. Please use the maven-publish plugin instead. Consult the upgrading guide for further information: https://docs.gradle.org/6.7/userguide/upgrading_version_5.html#legacy_publication_system_is_deprecated_and_replaced_with_the_publish_plugins
	at common_49xbil2i4pu46ezahhf7x05bh.run(/home/runner/work/gretty/gretty/common.gradle:6)
	(Run with --stacktrace to get the full stack trace of this deprecation warning.)
```

```
> Configure project :extraResourceBases
Using method Project.afterEvaluate(Closure) when the project is already evaluated has been deprecated. This will fail with an error in Gradle 7.0. The configuration given is ignored because the project has already been evaluated. To apply this configuration, remove afterEvaluate. Consult the upgrading guide for further information: https://docs.gradle.org/6.7/userguide/upgrading_version_5.html#calling_project_afterevaluate_on_an_evaluated_project_has_been_deprecated
	at build_2oprxc1ykw5aln9k71z40kmyt.run(/home/runner/work/gretty/gretty/integrationTests/extraResourceBases/build.gradle:2)
	(Run with --stacktrace to get the full stack trace of this deprecation warning.)
```

```
> Task :farmJacoco:MyWebApp:farmIntegrationTestServerReport
Changing the value for a FileCollection with a final value has been deprecated. This will fail with an error in Gradle 7.0. See https://docs.gradle.org/6.7/userguide/lazy_configuration.html#unmodifiable_property for more details.
	at build_5zpqcjazwidmxncis5rcjm393$_run_closure3$_closure7$_closure9$_closure10.doCall(/home/runner/work/gretty/gretty/integrationTests/farmJacoco/MyWebApp/build.gradle:45)
	(Run with --stacktrace to get the full stack trace of this deprecation warning.)
```

 Anyone up for the task to try them?

**Comment by wolfs** [comment]
For the plugin to be compatible with Gradle 7.0, only `> Task :farmJacoco:MyWebApp:farmIntegrationTestServerReport` needs to be fixed, the other warnings are about the build of the Gretty plugin itself, so the plugin would be compatible, but the build of the plugin wouldn't.

For fixing `The maven plugin has been deprecated.`, I suppose this can be fixed since the bintray plugin doesn't depend on the Maven plugin any more, I think. So I could try to remove the Maven plugin usage, so I can't really test it out. Is the Maven publishing used for anything any more?

**Comment by boris-petrov** [comment]
Yes, I would like for the plugin to also be built on Gradle 7 so it would be nice to fix all three. But right, it's more important to be able to support users using Gradle 7 so we can start only with that.

I really don't know about publishing. @javabrett does that. We've been trying with him to make it possible for me to also publish and we almost did that but then the Bintray saga came along... I'll speak with him over the next few days and we'll see.

**Comment by wolfs** [comment]
@boris-petrov I created a PR to fix the `Changing the value for a FileCollection with a final value` deprecation warning: https://github.com/gretty-gradle-plugin/gretty/pull/198

**Comment by wolfs** [comment]
> The two branches are OK for releasing now (as long as there are no issues with publishing), aren't they?

I think so. I just tried out the plugin from the 3.x branch with Gradle 7 and everything seems to work!

**Comment by f4lco** [comment]
@boris-petrov except that I once more vote for a beta version of 4.x as per https://github.com/gretty-gradle-plugin/gretty/issues/183#issuecomment-741860048. Maybe it is time to define what to do if Logback is effectively dead (or equivalently, Logback permanently drops the features Gretty relies on). But that must happen as part of #183.

**Comment by boris-petrov** [comment]
@f4lco - I mostly was talking about a 3.0.4 release because that's what 99% of the people are using anyways... but yes, I'm totally fine with a beta version for 4. Let's first see how things go with publishing as we need @javabrett for that. :)

btw, if you have nothing to do, you could look at https://github.com/gretty-gradle-plugin/gretty/issues/141. :smile:

**Comment by boris-petrov** [comment]
I believe this issue is now resolved after @chali's latest contribution? @f4lco am I right?

**Comment by f4lco** [comment]
Yes, I think so 👍
