### ISSUE TITLE
JDK9 Tomcat8 testAll java.lang.NoSuchFieldException: loaderRef

### ISSUE THREAD

**Issue by javabrett** [gretty-gradle-plugin/gretty#20]
Saw this running `testAll` with JDK9:

```
Mar. 06, 2018 12:16:42 PM org.apache.coyote.AbstractProtocol pause
INFO: Pausing ProtocolHandler ["http-nio-8080"]
Mar. 06, 2018 12:16:42 PM org.apache.catalina.core.StandardService stopInternal
INFO: Stopping service Tomcat
Mar. 06, 2018 12:16:42 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesResourceBundles
WARNING: Failed to clear ResourceBundle references for web application [ROOT]
java.lang.NoSuchFieldException: loaderRef
        at java.base/java.lang.Class.getDeclaredField(Class.java:2368)
        at org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesResourceBundles(WebappClassLoaderBase.java:2402)
        at org.apache.catalina.loader.WebappClassLoaderBase.clearReferences(WebappClassLoaderBase.java:1617)
        at org.apache.catalina.loader.WebappClassLoaderBase.stop(WebappClassLoaderBase.java:1537)
        at org.apache.catalina.loader.WebappLoader.stopInternal(WebappLoader.java:446)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:221)
        at org.apache.catalina.core.StandardContext.stopInternal(StandardContext.java:5572)
        at org.apache.catalina.util.LifecycleBase.stop(LifecycleBase.java:221)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1424)
        at org.apache.catalina.core.ContainerBase$StopChild.call(ContainerBase.java:1413)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.base/java.lang.Thread.run(Thread.java:844)
```

Note that this seems to be a clean-up exception only, and does not impact nor fail the test.

**Comment by javabrett** [comment]
Problem code in Tomcat was actually removed later in the 8.0 branch (this from Git-mirror):

```
$ git log --stat -G loaderRef
commit d2e6f10539ebcd2c5770097b43a8b1f9b15db7b4
Author: Mark Thomas <markt@apache.org>
Date:   Wed Oct 18 13:23:27 2017 +0000

    Remove the ResourceBundle memory leak protection since I am as sure as I can be
    that the original report was a false positive.
    ResourceBundle uses a WeakReference and it is likely what was originally observed was an instance of the genuine GC root not being visible in the profiler.
    
    git-svn-id: https://svn.apache.org/repos/asf/tomcat/tc8.0.x/trunk@1812511 13f79535-47bb-0310-9956-ffa450edef68

 java/org/apache/catalina/loader/WebappClassLoaderBase.java | 99 ---------------------------------------------------------------------------------------------------
 1 file changed, 99 deletions(-)

commit 6575769bc56f72a629c70bb41f26e6eef5b7c2bc
Author: Mark Thomas <markt@apache.org>
Date:   Mon Sep 8 11:13:06 2014 +0000

    Fix https://issues.apache.org/bugzilla/show_bug.cgi?id=56530
    Add a web application class loader implementation that supports the parallel loading of web application classes.
    
    git-svn-id: https://svn.apache.org/repos/asf/tomcat/trunk@1623360 13f79535-47bb-0310-9956-ffa450edef68

 java/org/apache/catalina/loader/WebappClassLoader.java     | 2798 ++---------------------------------------------------------------------------------------------------------------------------------------------
 java/org/apache/catalina/loader/WebappClassLoaderBase.java | 2788 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 2 files changed, 2816 insertions(+), 2770 deletions(-)

commit dae681a94cbedefcd47441805c7ea16468cf6555
Author: Mark Thomas <markt@apache.org>
Date:   Thu Feb 11 18:09:08 2010 +0000

    Improved memory leak prevention for resource ResourceBundle
    
    git-svn-id: https://svn.apache.org/repos/asf/tomcat/trunk@909097 13f79535-47bb-0310-9956-ffa450edef68

 java/org/apache/catalina/loader/WebappClassLoader.java | 84 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
 1 file changed, 84 insertions(+)
```
So a Tomcat 8.0.x version update or switch to Tomcat 8.5.x (#30) would fix this.

**Comment by henrik242** [comment]
So since #30 is fixed, can we close this issue to?

**Comment by javabrett** [comment]
Yes testing this for both Tomcat 8.0 (8.0.51) and 8.5 (8.5.30) for pre 3.0 master @ 6969ac728b7aa05f25b3278199c43f1fc4e8ef57 and they passed tests under JDK9.
