### ISSUE TITLE
GradleScopeServices has been closed

### ISSUE THREAD

**Issue by mvysny** [gretty-gradle-plugin/gretty#222]
Running the https://github.com/mvysny/karibu10-helloworld-application branch v14 with Gretty 3.0.4 and Gradle 7 works well, excellent work :+1: However there is the following exception printed in the stdout; it might be an indication of some deeper issue?

```
org.akhikhl.gretty.JettyScannerManager$1@9d99dd6 failed on '[/home/mavi/work/my/vok/karibu10-helloworld-application/build/vaadin-generated/META-INF/VAADIN/config/flow-build-info.json]
java.lang.IllegalStateException: GradleScopeServices has been closed.
        at org.gradle.internal.service.DefaultServiceRegistry.serviceRequested(DefaultServiceRegistry.java:268)
        at org.gradle.internal.service.DefaultServiceRegistry.getService(DefaultServiceRegistry.java:309)
        at org.gradle.internal.service.DefaultServiceRegistry.find(DefaultServiceRegistry.java:304)
        at org.gradle.internal.service.DefaultServiceRegistry.get(DefaultServiceRegistry.java:289)
        at org.gradle.invocation.DefaultGradle_Decorated.getCurrentGradleInstallation(Unknown Source)
        at org.gradle.invocation.DefaultGradle.getGradleHomeDir(DefaultGradle.java:167)
        at org.gradle.invocation.DefaultGradle_Decorated.getGradleHomeDir(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaBeanProperty.getProperty(MetaBeanProperty.java:59)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:233)
        at org.gradle.internal.metaobject.BeanDynamicObject.tryGetProperty(BeanDynamicObject.java:176)
        at org.gradle.internal.metaobject.CompositeDynamicObject.tryGetProperty(CompositeDynamicObject.java:55)
        at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:60)
        at org.gradle.invocation.DefaultGradle_Decorated.getProperty(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PogoGetPropertySite.getProperty(PogoGetPropertySite.java:49)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:329)
        at org.akhikhl.gretty.scanner.BaseScannerManager$_scanFilesChanged_closure8.doCall(BaseScannerManager.groovy:238)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.callClosureForMapEntry(DefaultGroovyMethods.java:5947)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2395)
        at org.codehaus.groovy.runtime.dgm$201.invoke(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:247)
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:56)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at org.akhikhl.gretty.scanner.BaseScannerManager.scanFilesChanged(BaseScannerManager.groovy:233)
        at org.akhikhl.gretty.JettyScannerManager.access$0(JettyScannerManager.groovy)
        at org.akhikhl.gretty.JettyScannerManager$1.filesChanged(JettyScannerManager.groovy:33)
        at org.eclipse.jetty.util.Scanner.reportBulkChanges(Scanner.java:691)
        at org.eclipse.jetty.util.Scanner.reportDifferences(Scanner.java:551)
        at org.eclipse.jetty.util.Scanner.scan(Scanner.java:403)
        at org.eclipse.jetty.util.Scanner$1.run(Scanner.java:353)
        at java.base/java.util.TimerThread.mainLoop(Timer.java:556)
        at java.base/java.util.TimerThread.run(Timer.java:506)
```

The file is modified by the `vaadinPrepareFrontend` task which is run before `processResources`/`appRun` task... but the `vaadinPrepareFrontend`+`appRun` tasks shouldn't be running in parallel so I wonder why Gradle notifies Gretty of changes... :thinking:

**Comment by boris-petrov** [comment]
@mvysny - thanks for the report. I can't seem to reproduce what you see. I cloned the repo and did a `./gradlew appRun` in it. It ran and seems to work. I don't see that exception. Am I doing something wrong? Or I'm missing some step? You have local changes?

@f4lco - any ideas?

**Comment by f4lco** [comment]
@boris-petrov no, I also currently lack reproduction of the error. For the record, the following line is mentioned in the stacktrace above:

https://github.com/gretty-gradle-plugin/gretty/blob/2ec6f70ea58e4cc621898a4d804204b7451b87fb/libs/gretty/src/main/groovy/org/akhikhl/gretty/scanner/BaseScannerManager.groovy#L238

It definitely can be indication of a problem, but it's hard to analyze further without knowing how to trigger this behavior.

**Comment by mvysny** [comment]
Hello everyone, thank you so much for looking into this.

Huh, I can't reproduce the issue today either. I was thinking that perhaps the issue only manifests when there's already a gradle daemon running, but that doesn't appear to be the case - I've tried the same steps both with gradle daemon running and with no daemon running, but I can't reproduce the issue anymore.

Since the issue manifests "randomly" (or perhaps only on an even day :-D ), I'm inclined to believe that this is a bug in Gradle. I'll close this report; when the issue manifests again I'll open a new report to the Gradle guys.

**Comment by boris-petrov** [comment]
@mvysny - thank you too! If you manage to reproduce it somehow, be sure to also let us know. Perhaps linking the Gradle issue so we can keep track also.
