### ISSUE TITLE
JDK9 Jasper/JSPC for Jetty 9.4.8.v20171121 is not fully JDK9-ready

### ISSUE THREAD

**Issue by javabrett** [gretty-gradle-plugin/gretty#23]
I'm seeing some JSPC/Jasper JSP-compilation issues with JDK9 running `testAll`.  Not sure yet if related, but I notice via https://github.com/eclipse/jetty.project/issues/2079 that Jetty 9.4.8.v20171121 running Jasper 8.5.23 is not 100% JDK9-ready.  The first such Jasper release is 8.5.24, which is on the Jetty 9.4.x branch presumably to be released as 9.4.9.  Snapshots are available.

We will need to determine whether its worth pulling in a Jetty 9.4.9 snapshot to see if it addresses JDK9 test-issues in order to continue, or wait for 9.4.9 release.

**Comment by henrik242** [comment]
I bumped the 9.4 jetty version, are you still seeing issues? Are you able to reproduce with a test?

**Comment by javabrett** [comment]
> I bumped the 9.4 jetty version, are you still seeing issues? Are you able to reproduce with a test?

@henrik242 Yes, during the review of #42 I built-out the full matrix, see https://github.com/javabrett/gretty/commit/3e3f2a5e3f78ca6fa69c4b902a1eda92f25b851a and https://travis-ci.org/javabrett/gretty/builds/374359746 .

JDK9 fails like this:

### jetty9

https://travis-ci.org/javabrett/gretty/jobs/374359763#L2396

```
May 03, 2018 11:55:30 AM org.apache.jasper.compiler.Compiler generateClass
SEVERE: Error compiling file: /home/travis/build/javabrett/gretty/integrationTests/extraResourceBases/build/serverBaseDir_jetty9/webapps-exploded/extraResourceBases/jsp/org/apache/jsp/index_html.java
11:55:30 WARN  
org.apache.jasper.JasperException: PWC6033: Error in Javac compilation for JSP
PWC6199: Generated servlet error:
package org.apache.jasper.runtime does not exist
```

### tomcat9

https://travis-ci.org/javabrett/gretty/jobs/374359767#L2797

```
WARNING: The following warnings have been detected: WARNING: HK2 service reification failed for [org.glassfish.jersey.message.internal.DataSourceProvider] with an exception:
MultiException stack 1 of 2
java.lang.NoClassDefFoundError: javax/activation/DataSource
	at java.base/java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredConstructors(Class.java:3110)
	at java.base/java.lang.Class.getDeclaredConstructors(Class.java:2314)
	at org.jvnet.hk2.internal.Utilities$5.run(Utilities.java:1352)
	at org.jvnet.hk2.internal.Utilities$5.run(Utilities.java:1348)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at org.jvnet.hk2.internal.Utilities.getAllConstructors(Utilities.java:1348)
	at org.jvnet.hk2.internal.Utilities.findProducerConstructor(Utilities.java:1269)
	at org.jvnet.hk2.internal.DefaultClassAnalyzer.getConstructor(DefaultClassAnalyzer.java:78)
	at org.glassfish.jersey.internal.inject.JerseyClassAnalyzer.getConstructor(JerseyClassAnalyzer.java:143)
	at org.jvnet.hk2.internal.Utilities.getConstructor(Utilities.java:199)
	at org.jvnet.hk2.internal.ClazzCreator.initialize(ClazzCreator.java:129)
	at org.jvnet.hk2.internal.ClazzCreator.initialize(ClazzCreator.java:182)
	at org.jvnet.hk2.internal.SystemDescriptor.internalReify(SystemDescriptor.java:723)
	at org.jvnet.hk2.internal.SystemDescriptor.reify(SystemDescriptor.java:678)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.reifyDescriptor(ServiceLocatorImpl.java:415)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.narrow(ServiceLocatorImpl.java:2122)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.access$900(ServiceLocatorImpl.java:120)
	at org.jvnet.hk2.internal.ServiceLocatorImpl$9.compute(ServiceLocatorImpl.java:1257)
	at org.jvnet.hk2.internal.ServiceLocatorImpl$9.compute(ServiceLocatorImpl.java:1252)
	at org.glassfish.hk2.utilities.cache.LRUHybridCache$OriginThreadAwareFuture$1.call(LRUHybridCache.java:115)
	at org.glassfish.hk2.utilities.cache.LRUHybridCache$OriginThreadAwareFuture$1.call(LRUHybridCache.java:111)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.glassfish.hk2.utilities.cache.LRUHybridCache$OriginThreadAwareFuture.run(LRUHybridCache.java:173)
	at org.glassfish.hk2.utilities.cache.LRUHybridCache.compute(LRUHybridCache.java:292)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetAllServiceHandles(ServiceLocatorImpl.java:1330)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServiceHandles(ServiceLocatorImpl.java:1239)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getAllServiceHandles(ServiceLocatorImpl.java:1228)
	at org.glassfish.jersey.internal.inject.Providers.getServiceHandles(Providers.java:352)
	at org.glassfish.jersey.internal.inject.Providers.getCustomProviders(Providers.java:200)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.<init>(MessageBodyFactory.java:303)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488)
	at org.glassfish.hk2.utilities.reflection.ReflectionHelper.makeMe(ReflectionHelper.java:1107)
	at org.jvnet.hk2.internal.ClazzCreator.createMe(ClazzCreator.java:274)
	at org.jvnet.hk2.internal.ClazzCreator.create(ClazzCreator.java:368)
	at org.jvnet.hk2.internal.SystemDescriptor.create(SystemDescriptor.java:471)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:114)
	at org.jvnet.hk2.internal.SingletonContext$1.compute(SingletonContext.java:102)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture$1.call(Cache.java:97)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.glassfish.hk2.utilities.cache.Cache$OriginThreadAwareFuture.run(Cache.java:154)
	at org.glassfish.hk2.utilities.cache.Cache.compute(Cache.java:199)
	at org.jvnet.hk2.internal.SingletonContext.findOrCreate(SingletonContext.java:153)
	at org.jvnet.hk2.internal.Utilities.createService(Utilities.java:2270)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.internalGetService(ServiceLocatorImpl.java:687)
	at org.jvnet.hk2.internal.ServiceLocatorImpl.getService(ServiceLocatorImpl.java:652)
	at org.glassfish.jersey.server.model.ComponentModelValidator.<init>(ComponentModelValidator.java:97)
	at org.glassfish.jersey.server.ApplicationHandler.initialize(ApplicationHandler.java:494)
	at org.glassfish.jersey.server.ApplicationHandler.access$500(ApplicationHandler.java:167)
	at org.glassfish.jersey.server.ApplicationHandler$3.run(ApplicationHandler.java:327)
	at org.glassfish.jersey.internal.Errors$2.call(Errors.java:289)
	at org.glassfish.jersey.internal.Errors$2.call(Errors.java:286)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.processWithException(Errors.java:286)
	at org.glassfish.jersey.server.ApplicationHandler.<init>(ApplicationHandler.java:324)
	at org.glassfish.jersey.servlet.WebComponent.<init>(WebComponent.java:315)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:170)
	at org.glassfish.jersey.servlet.ServletContainer.init(ServletContainer.java:358)
	at javax.servlet.GenericServlet.init(GenericServlet.java:158)
	at org.apache.catalina.core.StandardWrapper.initServlet(StandardWrapper.java:1124)
```

**Comment by javabrett** [comment]
Actually I think the Jetty9 failures are caused by the integration-tests running Jetty 9.2 and not 9.4.

**Comment by javabrett** [comment]
Resolving this:
- Some confusion here was that Jetty 9.2 was running, not 9.4.x
- We have upgraded to latest 9.4.x (9.4.10) and whilst it is not yet running integration-tests on master, it hopefully will soon and does not exhibit this issue under JDK9.
