### ISSUE TITLE
No such property: CONTAINER_JAR_PATTERN for class: org.eclipse.jetty.webapp.MetaInfConfiguration

### ISSUE THREAD

**Issue by jeffreyschultz** [gretty-gradle-plugin/gretty#286]
When running `jettyRunWar` in a Gradle project for a `create-react-app` project, gretty throws an error complaining about a missing property CONTAINER_JAR_PATTERN. I am not sure what to make of this, and if this is an issue in my configuration.

Also, when this failure takes place it doesn't kill Jetty and it continues to run in the background. This keeps the task from being executed again before killing the Gradle Daemons as `jettyStop` does not work after that failure.

Gradle 7.6

openjdk version "17" 2021-09-14
OpenJDK Runtime Environment (build 17+35-2724)
OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)

Gretty 4.0.3

```
apply plugin: "war"
apply plugin: "org.gretty"

apply from: "$rootDir/gradle/node.gradle"

task npmBuild(type: NpmTask) {
    dependsOn npmInstall

    inputs.files fileTree("src")
    inputs.files fileTree("public")
    inputs.files fileTree("node_modules")
    inputs.files file("package.json")
    inputs.files file("package-lock.json")
    outputs.files fileTree("$buildDir/webapp")

    args = ["run", "build"]
}

gretty {
    contextPath = "/admin"
}

war {
    dependsOn npmBuild
    webAppDirectory = file("$buildDir/webapp")
}
```

```
groovy.lang.MissingPropertyException: No such property: CONTAINER_JAR_PATTERN for class: org.eclipse.jetty.webapp.MetaInfConfiguration
	at groovy.lang.MetaClassImpl.invokeStaticMissingProperty(MetaClassImpl.java:1019)
	at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1963)
	at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1938)
	at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:3843)
	at org.codehaus.groovy.runtime.callsite.ClassMetaClassGetPropertySite.getProperty(ClassMetaClassGetPropertySite.java:50)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callGetProperty(AbstractCallSite.java:329)
	at org.akhikhl.gretty.JettyConfigurerImpl.createWebAppContext(JettyConfigurerImpl.groovy:206)
	at org.akhikhl.gretty.JettyConfigurer$createWebAppContext$5.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148)
	at org.akhikhl.gretty.JettyServerConfigurer.createContext(JettyServerConfigurer.groovy:74)
	at org.akhikhl.gretty.JettyServerConfigurer.createContext(JettyServerConfigurer.groovy)
	at org.akhikhl.gretty.JettyServerConfigurer$createContext$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:157)
	at org.akhikhl.gretty.JettyServerManager.startServer(JettyServerManager.groovy:58)
	at org.akhikhl.gretty.ServerManager$startServer$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
	at org.akhikhl.gretty.Runner.run(Runner.groovy:135)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
	at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:73)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
	at org.akhikhl.gretty.Runner.main(Runner.groovy:51)
16:27:12 INFO  Jetty 11.0.11 started and listening on port 8080
> Task :modules:ion-admin-ui:jettyRunWar FAILED
```

**Comment by jeffreyschultz** [comment]
I found another previous issue that turned out to be the Spring Dependency Management plugin. It seems like this is the case for me as well.

**Comment by boris-petrov** [comment]
@jeffreyschultz which one?

**Comment by f4lco** [comment]
@boris-petrov probably https://github.com/gretty-gradle-plugin/gretty/issues/248#issuecomment-1031375678, best guess 🙃

**Comment by jeffreyschultz** [comment]
> @jeffreyschultz which one?

yes, if was #248 as @f4lco mentioned.
