### ISSUE TITLE
Gradle 8 deprecation warnings

### ISSUE THREAD

**Issue by boris-petrov** [gretty-gradle-plugin/gretty#288]
When `appStart` on Gradle 8 the following 2 deprecation warnings can be seen:

```
Invocation of Task.project at execution time has been deprecated. This will fail with an error in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.2.1/userguide/upgrading_version_7.html#task_project
        at org.gradle.configurationcache.DeprecatedFeaturesListener.nagUserAbout(DeprecatedFeaturesListener.kt:81)
        at org.gradle.configurationcache.DeprecatedFeaturesListener.onProjectAccess(DeprecatedFeaturesListener.kt:54)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:472)
        at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:454)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:83)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:69)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:443)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:431)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:43)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:66)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:443)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast.dispatch(DefaultListenerManager.java:232)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast.dispatch(DefaultListenerManager.java:203)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at jdk.proxy1/jdk.proxy1.$Proxy72.onProjectAccess(Unknown Source)
        at org.gradle.configurationcache.AbstractTaskProjectAccessChecker.notifyProjectAccess(TaskExecutionAccessCheckers.kt:33)
        at org.gradle.api.internal.AbstractTask.getProject(AbstractTask.java:238)
        at org.gradle.api.DefaultTask.getProject(DefaultTask.java:59)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at groovy.lang.MetaBeanProperty.getProperty(MetaBeanProperty.java:59)
        at org.akhikhl.gretty.AppStartTask_Decorated.getProperty(Unknown Source)
        at org.akhikhl.gretty.AppStartTask.getStartConfig(AppStartTask.groovy:57)
        at org.akhikhl.gretty.AppStartTask_Decorated.getStartConfig(Unknown Source)
        at org.akhikhl.gretty.StartBaseTask.getLauncherConfig(StartBaseTask.groovy:172)
        at org.akhikhl.gretty.StartBaseTask.action(StartBaseTask.groovy:53)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
        ...
```

```
Invocation of Task.extensions at execution time has been deprecated. This will fail with an error in Gradle 9.0. Consult the upgrading guide for further information: https://docs.gradle.org/8.2.1/userguide/upgrading_version_8.html#task_convention
        at org.gradle.configurationcache.DeprecatedFeaturesListener.nagUserAbout(DeprecatedFeaturesListener.kt:81)
        at org.gradle.configurationcache.DeprecatedFeaturesListener.onConventionAccess(DeprecatedFeaturesListener.kt:66)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:472)
        at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:454)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:83)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:69)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:443)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:431)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:43)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:66)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:443)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast.dispatch(DefaultListenerManager.java:232)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast.dispatch(DefaultListenerManager.java:203)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
        at jdk.proxy1/jdk.proxy1.$Proxy72.onConventionAccess(Unknown Source)
        at org.gradle.configurationcache.AbstractTaskProjectAccessChecker.notifyConventionAccess(TaskExecutionAccessCheckers.kt:45)
        at org.gradle.api.internal.AbstractTask.notifyConventionAccess(AbstractTask.java:1073)
        at org.gradle.api.internal.AbstractTask.getConventionVia(AbstractTask.java:604)
        at org.gradle.api.internal.AbstractTask.getExtensions(AbstractTask.java:600)
        at org.gradle.api.DefaultTask.getExtensions(DefaultTask.java:324)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at groovy.lang.MetaBeanProperty.getProperty(MetaBeanProperty.java:59)
        at org.akhikhl.gretty.AppStartTask_Decorated.getProperty(Unknown Source)
        at org.akhikhl.gretty.StartBaseTask$_initJacoco_closure7.doCall(StartBaseTask.groovy:156)
        at org.akhikhl.gretty.StartBaseTask$_initJacoco_closure7.doCall(StartBaseTask.groovy)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at jdk.proxy6/jdk.proxy6.$Proxy143.getJacoco(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.akhikhl.gretty.StartBaseTask.getJacoco(StartBaseTask.groovy:145)
        at org.akhikhl.gretty.AppStartTask_Decorated.getJacoco(Unknown Source)
        at org.akhikhl.gretty.StartBaseTask.doPrepareServerConfig(StartBaseTask.groovy:107)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.akhikhl.gretty.AppStartTask.getStartConfig(AppStartTask.groovy:60)
        at org.akhikhl.gretty.AppStartTask_Decorated.getStartConfig(Unknown Source)
        at org.akhikhl.gretty.StartBaseTask.getLauncherConfig(StartBaseTask.groovy:172)
        at org.akhikhl.gretty.StartBaseTask.action(StartBaseTask.groovy:53)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:125)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:58)
        ...
```

**Comment by eskatos** [comment]
Gradle 9.0 is around the corner. These deprecated methods will be removed and this plugin will stop working.
