### ISSUE TITLE
JettyRestart task fails with MissingMethodException: No signature of method: org.akhikhl.gretty.JettyServerManager.startServer

### ISSUE THREAD

**Issue by smhc** [gretty-gradle-plugin/gretty#293]
Using the helloGretty example;
- Start the app via 'gradle apprun' in one terminal
- Restart the app using 'gradle jettyrestart' in another terminal

This worked ok in Gretty 3.0.9, but started failing in Gretty 3.1.0+ (still failing in 4.1.0).
(Gradle version 7.4.2, Java - openjdk 17.0.3)

The exception thrown is:

```

2023-08-23 14:51:03.177:INFO :oejs.Server:main: Stopped Server@49aa766b{STOPPING}[11.0.15,sto=0]
2023-08-23 14:51:03.181:INFO :oejs.AbstractConnector:main: Stopped ServerConnector@62515a47{HTTP/1.1, (http/1.1)}{0.0.0.0:8080}
2023-08-23 14:51:03.185:INFO :oejsh.ContextHandler:main: Stopped o.a.g.JettyWebAppContext@15f8701f{/helloGretty4,/helloGretty4,null,STOPPED}{/helloGretty4/build/libs/helloGretty.war}
Exception in thread "main" groovy.lang.MissingMethodException: No signature of method: org.akhikhl.gretty.JettyServerManager.startServer() is applicable for argument types: (null) values: [null]
Possible solutions: startServer(), stopServer()
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:70)
        at org.codehaus.groovy.runtime.callsite.PojoMetaClassSite.call(PojoMetaClassSite.java:46)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:139)
        at org.akhikhl.gretty.Runner.run(Runner.groovy:81)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:193)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:73)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:130)
        at org.akhikhl.gretty.Runner.main(Runner.groovy:35)
Exception in thread "Thread-275" org.gradle.process.internal.ExecException: Process 'command '/java'' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:414)
        at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:52)
        at org.gradle.process.internal.DefaultExecActionFactory.javaexec(DefaultExecActionFactory.java:198)
        at org.gradle.api.internal.project.DefaultProject.javaexec(DefaultProject.java:1160)
        at org.gradle.api.internal.project.DefaultProject.javaexec(DefaultProject.java:1155)
        at org.gradle.api.Project$javaexec$6.call(Unknown Source)
        at org.akhikhl.gretty.DefaultLauncher.javaExec(DefaultLauncher.groovy:84)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:362)
        at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:61)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:185)
        at org.akhikhl.gretty.LauncherBase$_launchThread_closure3.doCall(LauncherBase.groovy:199)
        at org.akhikhl.gretty.LauncherBase$_launchThread_closure3.doCall(LauncherBase.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:107)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:274)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1035)
        at groovy.lang.Closure.call(Closure.java:412)
        at groovy.lang.Closure.call(Closure.java:406)
        at groovy.lang.Closure.run(Closure.java:493)
        at java.base/java.lang.Thread.run(Thread.java:833)
```

**Comment by smhc** [comment]
I assume this is probably related to the class loader rework done in 3.1.0, in particular this functionality:

https://github.com/gretty-gradle-plugin/gretty/commit/0b7e7d938d04dba1ada324cf248cc58038e2fe99#diff-9e85d6aecfdcf12f882b002497ecef6ed29b3cc7419e8b62d911240d681a67e1R122

Is it just a matter of getting rid of the null param to startServer?

https://github.com/gretty-gradle-plugin/gretty/blob/master/libs/gretty-runner/src/main/groovy/org/akhikhl/gretty/Runner.groovy#L81

**Comment by boris-petrov** [comment]
@smhc indeed, it seems that this `null` parameter was forgotten. Thanks for mentioning that and finding the solution! I'll fix it and we'll see about releasing a new version soon.

**Comment by smhc** [comment]
Thanks for the response. I haven't confirmed if it fixes the issue, a quick experiment with the change showed further problems:

```
Exception in thread "main" java.lang.ClassNotFoundException: org.eclipse.jetty.server.Server
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
```

But that might be an issue on our end we need to address.

If a fix is developed, will there be a release in the 3.x stream? We are currently tied to using Jetty 10 and bound to gretty 3.x as a result.

**Comment by boris-petrov** [comment]
For sure there will be a 3.x release (hopefully soon). We'll support it for the foreseeable future.

**Comment by smhc** [comment]
I've raised https://github.com/gretty-gradle-plugin/gretty/pull/294 to fix additional issues with the restart command using the incorrect class loader. Can be confirmed with the 'helloGretty' restart as per initial issue.

**Comment by boris-petrov** [comment]
I believe this has been fixed (please reopen if it hasn't!). I'll try to create a new release next week. Thanks for the help!
