### ISSUE TITLE
Upgrade Tomcat 8.0.x support to 8.5.x

### ISSUE THREAD

**Issue by javabrett** [gretty-gradle-plugin/gretty#30]
Tomcat 8.0 was end-of-lifed and Tomcat 8.5 is a mostly drop-in replacement.  We should check whether the build and default Tomcat 8 can be easily switched to the Tomcat 8.5.x stream.

**Comment by javabrett** [comment]
Upgrade suffers the same issue as Tomcat 9 did in #25, which is not surprising since Tomcat 8.5 was derived from a pre-9 feature-branch.

```
Exception in thread "main" groovy.lang.ReadOnlyPropertyException: Cannot set readonly property: service for class: org.apache.catalina.startup.Tomcat
        at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:2744)
        at groovy.lang.MetaClassImpl.setProperty(MetaClassImpl.java:3770)
        at org.codehaus.groovy.runtime.InvokerHelper.setProperty(InvokerHelper.java:201)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.setProperty(ScriptBytecodeAdapter.java:484)
        at org.akhikhl.gretty.TomcatServerConfigurer.createAndConfigureServer(TomcatServerConfigurer.groovy:72)
        at org.akhikhl.gretty.TomcatServerConfigurer.createAndConfigureServer(TomcatServerConfigurer.groovy)
        at org.akhikhl.gretty.TomcatServerConfigurer$createAndConfigureServer.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
        at org.akhikhl.gretty.TomcatServerManager.startServer(TomcatServerManager.groovy:45)
        at org.akhikhl.gretty.ServerManager$startServer$0.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.akhikhl.gretty.Runner.run(Runner.groovy:117)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.call(PogoMetaMethodSite.java:71)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
        at org.akhikhl.gretty.Runner.main(Runner.groovy:44)
```

**Comment by henrik242** [comment]
We've been using tomcat8.5 with the "old" gretty for awhile, just by defining dependencies manually:
```
ext.versions = [
    tomcat: '8.5.28',
    groovy: '2.5.0-beta-3',
    jetty: '9.3.22.v20171030',
]

dependencies {
    gretty(
        "org.eclipse.jetty:jetty-server:${versions.jetty}",
        "org.eclipse.jetty:jetty-http:${versions.jetty}",
        "org.eclipse.jetty:jetty-util:${versions.jetty}",
        "org.eclipse.jetty:jetty-servlets:${versions.jetty}",
        "org.eclipse.jetty:jetty-webapp:${versions.jetty}",
        libs.commons_cli,
        "org.apache.tomcat.embed:tomcat-embed-core:${versions.tomcat}",
        "org.apache.tomcat.embed:tomcat-embed-el:${versions.tomcat}",
        "org.apache.tomcat.embed:tomcat-embed-jasper:${versions.tomcat}",
        "org.apache.tomcat.embed:tomcat-embed-websocket:${versions.tomcat}",
        "org.codehaus.groovy:groovy-all:${versions.groovy}",
        "io.dropwizard.metrics:metrics-core:${versions.metrics}"
    )
}
```
