### ISSUE TITLE
Remove usage of soon to be deprecated `Task.getProject`

### ISSUE THREAD

**Issue by abstratt** [gretty-gradle-plugin/gretty#313]
Please avoid using `Task.project` at execution time as in here:

https://github.com/gretty-gradle-plugin/gretty/blob/5b99776fe8f4f7c53cac6aef63950b9e5e345e6d/libs/gretty/src/main/groovy/org/akhikhl/gretty/StartBaseTask.groovy#L60C45-L60C52

as it is going to be deprecated in Gradle 8.12, and forbidden in a future Gradle release.

**Comment by boris-petrov** [comment]
@abstratt is this a new deprecation? Isn't this the same as #288 or it's something new?

**Comment by abstratt** [comment]
It is the same, or sort of. Before Gradle 8.12, you would only see that deprecation if enabling `STABLE_CONFIGURATION_CACHE` feature flag. From 8.12, users should see it regardless of that feature flag. Feel free to close as a duplicate, just beware it will be issued for all users, not only those enabling the feature flag.

**Comment by boris-petrov** [comment]
Ah, I see. Thanks for pointing that out. In any case, PRs are welcome for all deprecations!

**Comment by eskatos** [comment]
Turning this deprecation into an error has been postponed to Gradle 10.

**Comment by TWiStErRob** [comment]
I just tried 4.1.10 on Gradle 9.0.0 and this is an incarnation of this issue I believe:
`gradlew :farmRun --no-configuration-cache`
```
> Task :farmRun
Invocation of Task.project at execution time has been deprecated. This will fail with an error in Gradle 10. This API is incompatible with the configuration cache, which will become the only mode supported by Gradle in a future release. Consult the upgrading guide for further information: https://docs.gradle.org/9.0.0/userguide/upgrading_version_7.html#task_project
        at org.gradle.internal.cc.impl.DeprecatedFeaturesListener.nagUserAbout(DeprecatedFeaturesListener.kt:98)
        at org.gradle.internal.cc.impl.DeprecatedFeaturesListener.onProjectAccess(DeprecatedFeaturesListener.kt:70)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
        at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
        at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:587)
        at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:557)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:84)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:70)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:414)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:399)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:44)
        at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:67)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:414)
        at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:399)
        at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:92)
        at jdk.proxy1/jdk.proxy1.$Proxy134.onProjectAccess(Unknown Source)
        at org.gradle.internal.cc.impl.AbstractTaskProjectAccessChecker.notifyProjectAccess(TaskExecutionAccessCheckers.kt:47)
        at org.gradle.api.internal.AbstractTask.getProject(AbstractTask.java:240)
        at org.gradle.api.DefaultTask.getProject(DefaultTask.java:60)
        at org.akhikhl.gretty.FarmStartTask.getStartConfig(FarmStartTask.groovy:55)
        at org.akhikhl.gretty.FarmStartTask_Decorated.getStartConfig(Unknown Source)
        at org.akhikhl.gretty.StartBaseTask.getLauncherConfig(StartBaseTask.groovy:210)
        at org.akhikhl.gretty.StartBaseTask.action(StartBaseTask.groovy:66)
```

---

There are other mentions of `Project` when CC is not disabled:

`gradlew farmRun`
```
3 problems were found storing the configuration cache.
- Task `...:farmRun` of type `org.akhikhl.gretty.FarmStartTask`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
  See https://docs.gradle.org/9.0.0/userguide/configuration_cache_requirements.html#config_cache:requirements:disallowed_types
- Task `...:prepareInplaceWebAppFolder` of type `org.gradle.api.tasks.Copy`: cannot serialize object of type 'org.gradle.api.internal.project.DefaultProject', a subtype of 'org.gradle.api.Project', as these are not supported with the configuration cache.
  See https://docs.gradle.org/9.0.0/userguide/configuration_cache_requirements.html#config_cache:requirements:disallowed_types
- Task `...:prepareInplaceWebAppFolder` of type `org.gradle.api.tasks.Copy`: execution of task '...:prepareInplaceWebAppFolder' caused invocation of 'Task.project' in other task at execution time which is unsupported with the configuration cache.
  See https://docs.gradle.org/9.0.0/userguide/configuration_cache_requirements.html#config_cache:requirements:use_project_during_execution
```
