### ISSUE TITLE
Could not get unknown property 'mainClass' for object of type org.springframework.boot.gradle.dsl.SpringBootExtension.

### ISSUE THREAD

**Issue by tiemei** [gretty-gradle-plugin/gretty#70]
see： https://github.com/rssdev10/gretty/commit/583b2304d4a0d49e621648bc28253e5dda9788d0#diff-dce4984e08a1962cae1a388a6305a75a

gretty version: 2.2.0
spring boot version : 2.0.2.RELEASE

**Comment by tiemei** [comment]
not support spring boot 2.x.x ?

**Comment by rssdev10** [comment]
Hi, I merged yours 2.3.0-release branch into my repo and tried to rerun Boot2 app. It is not working but for now the reason is
```
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.server.session.HashSessionManager
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 41 more
Exception in thread "Thread-27" org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java'' finished with non-zero exit value 1
        at org.gradle.process.internal.DefaultExecHandle$ExecResultImpl.assertNormalExitValue(DefaultExecHandle.java:395)
        at org.gradle.process.internal.DefaultJavaExecAction.execute(DefaultJavaExecAction.java:37)
        at org.gradle.api.internal.file.DefaultFileOperations.javaexec(DefaultFileOperations.java:192)
```

I'm using very simple test. It is almost empty demo Boot2 app from https://start.spring.io/ with included gretty.

[demo-spring-boot-2_gretty-2-3 2.zip](https://github.com/gretty-gradle-plugin/gretty/files/2310427/demo-spring-boot-2_gretty-2-3.2.zip)

**Comment by weleoka** [comment]
The error is occuring for my running of Gretty tasks. If it is the case that `springBoot=true` in gradle.build is needed in order for Gretty to work with Spring?

Currently the dependency for `gretty-springboot-2.3.x` is failing.

**Comment by golinko** [comment]
Have the same issue as @weleoka , but for SpringBoot 2.1.6.RELEASE and Gradle 5.6.2

The commit mentioned by @tiemei should fix the problem with mainClass which is not present in springBoot properties anymore.

What needs to be done in order to release the fix?
