### ISSUE TITLE
Not working with Java 11 selecting Jetty9.4 as servlet container

### ISSUE THREAD

**Issue by ankurpathak** [gretty-gradle-plugin/gretty#88]
On running it with Java 11 and selecting jetty9.4 asservlet coontainer we end with following stack trace:
java.lang.RuntimeException: Error scanning file /home/ankur/Development/projects/gradle-web/build/classes/java/main/HelloWorldServlet.class
        at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:743) ~[jetty-annotations-9.4.9.v20180320.jar:9.4.9.v20180320]
        at org.eclipse.jetty.annotations.AnnotationParser.parse(AnnotationParser.java:829) ~[jetty-annotations-9.4.9.v20180320.jar:9.4.9.v20180320]
        at org.eclipse.jetty.annotations.AnnotationConfiguration$ParserTask.call(AnnotationConfiguration.java:163) ~[jetty-annotations-9.4.9.v20180320.jar:9.4.9.v20180320]
        at org.eclipse.jetty.annotations.AnnotationConfiguration$1.run(AnnotationConfiguration.java:471) ~[jetty-annotations-9.4.9.v20180320.jar:9.4.9.v20180320]
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:754) ~[jetty-util-9.4.9.v20180320.jar:9.4.9.v20180320]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:672) ~[jetty-util-9.4.9.v20180320.jar:9.4.9.v20180320]
        at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]
Caused by: java.lang.IllegalArgumentException: Unsupported class file major version 55
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166) ~[asm-6.1.1.jar:na]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:148) ~[asm-6.1.1.jar:na]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:136) ~[asm-6.1.1.jar:na]
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:237) ~[asm-6.1.1.jar:na]
        at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:932) ~[jetty-annotations-9.4.9.v20180320.jar:9.4.9.v20180320]
        at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:737) ~[jetty-annotations-9.4.9.v20180320.jar:9.4.9.v20180320]
        ... 6 common frames omitted

**Comment by javabrett** [comment]
ASM needs to be upgraded in-order to work with JDK11, see 1f77dcb9a0df92465e1939cdec4d42b61ae1a651 .  This is on master for Gretty 3.0, which is not yet released.

In the interim you might want to try a snapshot build from https://oss.jfrog.org/artifactory/oss-snapshot-local/org/gretty/gretty-core/3.0.0-SNAPSHOT/ , which should work with JDK11.

**Comment by vidanda** [comment]
Even with snapshot-3.0.0:
`
..........  
java.lang.NoClassDefFoundError: sun/reflect/Reflection
        at org.springsource.loaded.ri.ReflectiveInterceptor.getCallerClass(ReflectiveInterceptor.java:225)
        at org.springsource.loaded.ri.ReflectiveInterceptor.asAccessibleConstructor(ReflectiveInterceptor.java:603)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrConstructorNewInstance(ReflectiveInterceptor.java:1074)
        at org.codehaus.groovy.reflection.GroovyClassValueFactory.createGroovyClassValue(GroovyClassValueFactory.java:61)
        at org.codehaus.groovy.reflection.ClassInfo.<clinit>(ClassInfo.java:109)
        at org.codehaus.groovy.reflection.ReflectionCache.getCachedClass(ReflectionCache.java:110)
        at org.codehaus.groovy.reflection.ReflectionCache.<clinit>(ReflectionCache.java:55)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.registerMethods(MetaClassRegistryImpl.java:214)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:112)
        at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.<init>(MetaClassRegistryImpl.java:90)
        at groovy.lang.GroovySystem.<clinit>(GroovySystem.java:36)
        at org.codehaus.groovy.runtime.InvokerHelper.<clinit>(InvokerHelper.java:82)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.createCallConstructorSite(CallSiteArray.java:86)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:59)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:238)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:242)
        at org.akhikhl.gretty.Runner.main(Runner.groovy:40)
Caused by: java.lang.ClassNotFoundException: sun.reflect.Reflection
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 17 more . 
.......
`
